### PR TITLE
Landing page proposal

### PR DESCRIPTION
**Pull request by azubala**
What's up?
- this is my proposal of the landing page, based on free bootstrap template with Jekyll integration
- usage:
  - install bundler: `$ gem install bundler`
  - install gems: `$ bundle install`
  - run jekyll locally: `$ bundle exec jekyll serve` 
  - open http://0.0.0.0:4000

Jekyll structure:
- `_includes` contains modules of html pages included in the `default.html`
- `_posts` used for workshops description
- `_config.yml` base configuration for the page

### CODE REVIEW

**Comment by azubala** [comment]
@paweldudek @literator @lukewar please check this out!

**Comment by azubala** [comment]
TODO:
- [x] about content, file `about.md`
- [ ] workshop description and image (maybe some image from Kraków with Swift logo:) )
- [ ] logo text is not visible - add blur underneath
- [x] bottom contact photo does not match the top one (not sure if problem)
- [x] link proper Twitter account
- [ ] external links Twitter, Github, should open in new tab
- [ ] logo does not scale down properly on phone, hence layout is broken

**Comment by literator** [comment]
@azubala nice! Good start :)

**Comment by azubala** [comment]
Thanks! Let's improve this together, cause I'm noob in this area:)

**Comment by lukewar** [comment]
Maybe we should covert those tasks list into issues?

**Pull request merged**
